/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#adc6ff",
        "on-primary-container": "#00285d",
        "surface-bright": "#363941",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#00515d",
        "on-background": "#e1e2ec",
        "tertiary-fixed": "#ffdcc6",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-primary-fixed": "#001a42",
        "error-container": "#93000a",
        "inverse-surface": "#e1e2ec",
        "outline": "#8c909f",
        "secondary-fixed-dim": "#2fd9f4",
        "surface": "#10131a",
        "surface-variant": "#32353c",
        "inverse-primary": "#005ac2",
        "secondary": "#5de6ff",
        "primary-fixed": "#d8e2ff",
        "secondary-container": "#00cbe6",
        "tertiary-container": "#df7412",
        "on-surface": "#e1e2ec",
        "surface-container-highest": "#32353c",
        "surface-tint": "#adc6ff",
        "primary-container": "#4d8eff",
        "on-primary-fixed-variant": "#004395",
        "on-secondary-fixed-variant": "#004e5a",
        "on-secondary": "#00363e",
        "secondary-fixed": "#a2eeff",
        "on-secondary-fixed": "#001f25",
        "outline-variant": "#424754",
        "on-error": "#690005",
        "tertiary": "#ffb786",
        "surface-container-lowest": "#0b0e15",
        "inverse-on-surface": "#2e3038",
        "surface-dim": "#10131a",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary-fixed": "#311400",
        "on-tertiary-fixed-variant": "#723600",
        "on-tertiary": "#502400",
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-container": "#461f00",
        "surface-container-low": "#191b23",
        "surface-container": "#1d2027",
        "background": "#10131a",
        "surface-container-high": "#272a31",
        "on-primary": "#002e6a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "xl": "40px",
        "base": "4px",
        "xs": "4px",
        "lg": "24px",
        "gutter": "24px",
        "margin-desktop": "32px",
        "sm": "8px",
        "margin-mobile": "16px",
        "md": "16px"
      },
      fontFamily: {
        "display": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["13px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "1.0", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
